# Generated by Django 2.1.8 on 2019-06-01 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20190530_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='update_date',
        ),
    ]
